### ISSUE TITLE
Accents dans le sujet cause erreur

### ISSUE THREAD

**Issue by NancyRobertson** [NancyRobertson/cadre_familial#5]
Console log: 

Sujet: `Erica est la plus à droite`

```
OK ['nancy.robertson.estarling2@gmail.com authenticated (Success)']
Processing mailbox INBOX


Traceback (most recent call last):
  File "/usr/local/bin/cadre_familial.py", line 237, in <module>
    process_mailbox(M)
  File "/usr/local/bin/cadre_familial.py", line 202, in process_mailbox
    process_message(num, msg)
  File "/usr/local/bin/cadre_familial.py", line 157, in process_message
    print 'Message %s (%s): %s  from %s' % (num, message_id, subject, from_h)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 70: ordinal not in range(128)
Hello cadre01Vilmay@gmail.com
Hello cadre01Vilmay@gmail.com
Hello cadre01Vilmay@gmail.com
Fri Jul 26 13:03:01 EDT 2019
OK ['cadre03vilmay@gmail.com authenticated (Success)']
Processing mailbox INBOX
```

**Comment by NancyRobertson** [comment]
Fixed : https://github.com/NancyRobertson/cadre_familial/commit/b1eaaec3f23c352682eeb4651a2bd2b77d33a904
